---

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - 'merge-strategy: rebase'
      - 'type: dependencies'
      - 'github-actions'

...
